### ISSUE TITLE
Incorrect end date time in order info

### ISSUE THREAD

**Issue by gedex** [woothemes/woocommerce-accommodation-bookings#18]
PR #14 fixes the checkout date in cart page, but still incorrect in order confirmation.

We'll be using [`DateTime::createFromFormat`](http://php.net/manual/en/datetime.createfromformat.php), which means we'll bump required version of PHP to >= 5.3.

**Comment by solaceten** [comment]
Whilst this appears to be fixed in the customer UI, admin and emails, I am also seeing a section in the booking edit screen that does not show the check in / out times:

![edit booking missing time 2016-02-12 16-04-15](https://cloud.githubusercontent.com/assets/2679075/13010598/d57c8608-d1a2-11e5-8e0b-279b96dc1ad6.png)

**Comment by gedex** [comment]
@solaceten Good point. I was aware with that too. Probably will hide those fields and just display static text of time (both for check-in time and check-out time).
