### ISSUE TITLE
Fatal error with non-English languages

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce-accommodation-bookings#36]
```
<b>Fatal error</b>:  Call to a member function add() on a non-object in <b>/srv/www/wordpress-default/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-booking-order-info.php</b> on line <b>79</b><br />
```

This happens because `$start_date` returns the localized date, and the class `Date` can't handle that.

cc @gedex

**Comment by dwainm** [comment]
Thanks @SiR-DanieL . The issue is correct, but the problem is a deeper. Within bookings, we store the localised date string as part of the booking line item data. The issues is actually a bookings "core" issue. I've created the new issues here: https://github.com/woothemes/woocommerce-bookings/issues/676

**Comment by dwainm** [comment]
After looking at this some more I've decided to fix it up temporarily until we can change how booking dates are stored in https://github.com/woothemes/woocommerce-bookings/issues/676
