### ISSUE TITLE
Assets directory was not uploaded to the .org plugin repo for version 1.0.2

### ISSUE THREAD

**Issue by SiR-DanieL** [woothemes/woocommerce-accommodation-bookings#38]
Related to #35 

Ref: https://woothemes.zendesk.com/agent/tickets/391214

All the tabs created by the Accommodation extension are showing also on other product types, in the admin editing screen.
Eg. Rates.

I can reproduce the issue on my local setup.
I also tested on a fresh install with only WooCommerce Bookings and Accommodations active.

It not only happens with bookable products, but with any product type.

Waiting for FTP and WP Admin credentials in the ticket.

cc @gedex

**Comment by dwainm** [comment]
@SiR-DanieL please add the full issue description in you first comment.

**Comment by SiR-DanieL** [comment]
Done

**Comment by dwainm** [comment]
Thank you @SiR-DanieL!

**Comment by robertstaddon** [comment]
@SiR-DanieL, I believe the cause of this problem is that the current zipped plugin file on the WordPress repository does not contain the "assets" folder (See https://github.com/woothemes/woocommerce-accommodation-bookings/issues/39). Try downloading the plugin from here on GitHub and installing it. This fixed the problem for me.

**Comment by al3xstanhope** [comment]
I can confirm that @robertstaddon is bang on the money with his suggestion; downloading the zipped version from this here Github repository fixed the issue for me too!

**Comment by dwainm** [comment]
Fixed: https://plugins.svn.wordpress.org/woocommerce-accommodation-bookings/tags/1.0.3/
