### ISSUE TITLE
Fatal error: Allowed memory size

### ISSUE THREAD

**Issue by tunteam** [woothemes/woocommerce-accommodation-bookings#53]
I have 100's of bookable products and I am getting a fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 80 bytes), when I try to get to "All bookings", "Create booking" and Calendar.

I think it is caused by the select box trying to load all the avaiblable bookable products.

An ajax select box similar to the customer's one would be a solution to the issue.

**Comment by dwainm** [comment]
@tunteam thanks for reporting this here but it seems this issue is with the bookings plugin and not the accommodation bookings. In order for us to confirm we'll need one of our engineers to inspect your site. It may be a very specific to your site or a genuine bug. Please submit a support ticket here: https://support.woothemes.com/hc/en-us and we'll inspect this further.
