### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by wpgroun** [woothemes/woocommerce-accommodation-bookings#64]
I get error "Internal Server Error" when I am trying to pay with BACS

**Comment by gedex** [comment]
Hi @wpgroun,

Any error from the error log says about woocommerce-accommodation-bookings being the issue?

**Comment by wpgroun** [comment]
When I disable php debugs appears the message  "Internal Server Error". When I enable php debugs appers json error. 

I also noticed that when I am trying to pay with paypal, then the payment works fine from paypal but at backoffice is unpaid
Theme: enfold

**Comment by roykho** [comment]
Sorry I don't believe this to be an issue with this plugin. I would suggest you post this on https://wordpress.org/support/plugin/woocommerce

**Comment by cedriccharles4** [comment]
Hi @wpgroun !

I have the exact same issue. Did you find a solution ?

Thank you !

**Comment by jessepearson** [comment]
@cedriccharles4 This isn't a support forum, this is a place to report bugs when found. This issue is also over a year old. 

The first suggestion on what to do would be to turn on debugging and logging in WordPress. If you have FTP access, you can add these lines to your `wp-config.php` file to turn [debugging](https://codex.wordpress.org/Debugging_in_WordPress) on:

```
	define( 'WP_DEBUG', true );
	define( 'WP_DEBUG_LOG', true );
	define( 'WP_DEBUG_DISPLAY', false );
```

This will make any errors in WordPress output to a `debug.log` file. **Note**: there should be a rule already in place that looks like this `define( 'WP_DEBUG', false );`, you will want to replace this.

Once this is done, you can refresh the page that isn't loading and if there are any errors, they should be logged here: YOUR_DOMAIN/wp-content/debug.log

This will help you find out what is causing the error. If you are not able to figure it out, please submit a support ticket through your WooCommerce.com account.
