### ISSUE TITLE
Global Availability with Date Range + Time does not work

### ISSUE THREAD

**Issue by mikeyarce** [woothemes/woocommerce-accommodation-bookings#73]
#### What I expected

To be able to set Global Availability based on Times for Accommodations.

#### What happened instead

When I set a Global Availability of Date Range with Time, it is not applied to my Accommodation Bookings.

#### Steps to reproduce the issue

1. Create a new Accommodations Bookings product
2. Set Global Availability to not bookable for a Date range with Time:
![screen shot 2016-09-09 at 9 48 49 am](https://cloud.githubusercontent.com/assets/3220162/18395242/a3f2e12a-7672-11e6-9b78-c878445d18cc.png)
3. The result is that those dates are still bookable

-------------------
- [ ] Issue assigned to next milestone.
- [ ] Issue assigned a priority (will be assessed by maintainers).

**Comment by roykho** [comment]
So I believe that is the expected behavior as accommodation does not work with time in general. Even if you go to the product itself and see availability options, you will not see date range with time. I believe this is just something that needs to be documented while using global availability. Closing for now unless you have other thoughts?
